CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    author_id  BIGINT                                              NOT NULL,
    event_id   BIGINT                                              NOT NULL,
    text       VARCHAR(2000)                                       NOT NULL,
    created    TIMESTAMP                                           NOT NULL DEFAULT now(),
    updated    TIMESTAMP                                                    DEFAULT NULL,
    is_deleted BOOLEAN                                             NOT NULL DEFAULT false
);
