-- DROP TABLE IF EXISTS endpoint_hits CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app     VARCHAR(512)                            NOT NULL,
    uri     VARCHAR(512)                            NOT NULL,
    ip      VARCHAR(512)                            NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_endpoint_hits PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_ip ON endpoint_hits (ip);
CREATE INDEX IF NOT EXISTS idx_endpoint_hits_timestamp ON endpoint_hits (created);
