server:
  port: 0

aggregator:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      properties:
        "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
        "value.serializer": "ru.practicum.ewm.kafka.serializers.GeneralAvroSerializer"
        acks: "all"
        retries: 3
        "linger.ms": 5
        "request.timeout.ms": 30000
        "delivery.timeout.ms": 120000
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
      topic: "stats.events-similarity.v1"

    consumer:
      properties:
        "key.deserializer": "org.apache.kafka.common.serialization.StringDeserializer"
        "value.deserializer": "ru.practicum.ewm.kafka.deserializers.UserActionAvroDeserializer"
        "group.id": "aggregator-group"
        "enable.auto.commit": false
        "auto.commit.interval.ms": 0
        "auto.offset.reset": "earliest"
        "max.poll.records": 100
        "fetch.min.bytes": 1
        "fetch.max.wait.ms": 500
        "session.timeout.ms": 30000
        "heartbeat.interval.ms": 10000
        "bootstrap.servers": ${aggregator.kafka.bootstrap-servers}
      topic: stats.user-actions.v1
      poll-timeout: 100ms
