CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
--     CONSTRAINT fk_event_req FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
--     CONSTRAINT fk_requester_req FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
);