CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(250)                            NOT NULL,
    email VARCHAR(254)                            NOT NULL UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL UNIQUE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    annotation        VARCHAR(2000)                       NOT NULL,
    category_id       BIGINT REFERENCES categories (id) ON DELETE CASCADE,
    created           TIMESTAMP WITHOUT TIME ZONE         NOT NULL,
    description       VARCHAR(7000)                       NOT NULL,
    initiator_id      BIGINT REFERENCES users (id) ON DELETE CASCADE,
    event_date        TIMESTAMP WITHOUT TIME ZONE         NOT NULL,
    location_id       BIGINT REFERENCES locations (id) ON DELETE CASCADE,
    paid              BOOLEAN                             NOT NULL DEFAULT false,
    participant_limit INTEGER,
    published         TIMESTAMP WITHOUT TIME ZONE,
    moderate          BOOLEAN                             NOT NULL DEFAULT true,
    state             VARCHAR(20)                         NOT NULL,
    title             VARCHAR(120)                        NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    author_id  BIGINT REFERENCES users (id)                        NOT NULL,
    event_id   BIGINT REFERENCES events (id)                       NOT NULL,
    text       VARCHAR(2000)                                       NOT NULL,
    created    TIMESTAMP                                           NOT NULL DEFAULT now(),
    updated    TIMESTAMP                                                    DEFAULT NULL,
    is_deleted BOOLEAN                                             NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(50)                             NOT NULL,
    pinned BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilations FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT fk_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status       VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id),
    CONSTRAINT fk_event_req FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_requester_req FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
);
